[[constraint]]
  name = "github.com/Masterminds/sprig"
  version = "^2.15.0"

[[constraint]]
  name = "github.com/docker/go-units"
  version = "^0.3.3"

[[constraint]]
  name = "github.com/fatih/color"
  version = "^1.6.0"

[[constraint]]
  name = "github.com/olekukonko/tablewriter"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "^0.0.3"

[[constraint]]
  name = "gopkg.in/src-d/go-git.v4"
  version = "^4.3.1"

[prune]
  go-tests = true
  unused-packages = true
